home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('exp/', views.exp, name='exp'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
    path('semua/', views.semua, name='semua'),
    path('haltambah/', views.haltambah, name='haltambah'),
    path('tambah/', views.tambah, name="tambah"),
    path('semua/<int:pk>', views.hapus, name="hapus"),
    path('detail/<int:pk>', views.detail, name="detail"),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('story1/', views.story1, name='story1'),
   
]

story5/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1', include('story1.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('tambah/', views.tambahK, name='tambahK'),
    path('data/', views.dataK, name='dataK'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
   
]

home/models.py
from django.db import models

# Create your models here.
class Sched(models.Model):
    namaMatkul = models.CharField(max_length = 50)
    dosen = models.CharField(max_length = 50)
    sks = models.CharField(max_length = 50)
    deskripsi = models.CharField(max_length = 50)
    tahun = models.CharField(max_length = 50)
    ruang = models.CharField(max_length = 50)

story1/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length=50, null = True, blank= False)

    class Meta:
        db_table = 'Kegiatan'

    def __str__(self):
        return self.namaKegiatan

class Orang(models.Model):
    namaOrang = models.CharField(max_length=50, null=True, blank=False)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, null = True, blank = False)

    class Meta:
        db_table = 'Orang'

    def __str__(self):
        return self.namaOrang

story7/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import Sched

class Jadwal(forms.ModelForm):
    class Meta:
        model = Sched
        fields = '__all__'

story6/forms.py
from django import forms
from django.forms import fields
from .models import Kegiatan, Orang

class formOrang(forms.ModelForm):
    class Meta:
        model = Orang
        fields = '__all__'

class formKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

home/views.py
from django.shortcuts import render, redirect
from .models import Sched
from .forms import Jadwal

# Create your views here.
def index(request):
    context = {"check" :0}
    return render(request, 'index.html', context)

def exp(request):
    context = {"check" :1}
    return render(request, 'exp.html', context)

def gallery(request):
    context = {"check" :2}
    return render(request, 'gallery.html', context)

def contact(request):
    context = {"check" :3}
    return render(request, 'contact.html', context)

def semua(request):
    jad = Sched.objects.all()
    context = {"schedule": jad}
    return render(request, 'semua.html', context)

def haltambah(request):
    form = Jadwal()
    print("sad")
    if form.is_valid and request.method ==  "POST":
        form = Jadwal(request.POST)
        form.save()
        print("sukses")
        return redirect('/semua')
    else:
        context = {'form': form}
        return render(request, 'haltambah.html', context)

def tambah(request):
    fr = Jadwal()
    if fr.is_valid() and request.method ==  "POST":
        fr = Jadwal(request.POST)
        fr.save()
        return redirect('/semua')
    

def hapus(request, pk):
    jadw = Sched.objects.get(id = pk)
    jadw.delete()
    jad = Sched.objects.all()
    context = {"schedule": jad}
    return render(request, 'semua.html', context)

def detail(request, pk):
    ja = Sched.objects.all().filter(id=pk)
    context = {"schedule" : ja}
    return render(request, 'detail.html', context)
        
        

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    context = {"check" :4}
    return render(request, 'story1.html', context)

story6/views.py
from django.http import request
from django.shortcuts import render, redirect
from .models import Orang, Kegiatan
from .forms import formOrang, formKegiatan
# Create your views here.
def landing(request):
    return render(request, 'landing.html')

def tambahK(request):
    form = formKegiatan()
    if form.is_valid and request.method ==  "POST":
        form = formKegiatan(request.POST)
        form.save()
        return redirect('/story6/')
    else:
        context = {'form': form}
        return render(request, 'tambahK.html', context)

def dataK(request):
    form = formOrang()
    dataO = Orang.objects.all()
    dataKe = Kegiatan.objects.all()
    if form.is_valid and request.method ==  "POST":
        form = formOrang(request.POST)
        form.save()
        return redirect('/story6/data')
    else:
        context = {'form': form, 'dataO': dataO, 'dataKe': dataKe}
        return render(request, 'dataK.html', context) 

story7/views.py
from django.shortcuts import render

# Create your views here.
def story7(request):
    return render(request, 'story7.html')

home/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock meta %}
{% block content %}
      <div class="container cntct">
            <h3 class="text-center">You</h3>
            <h3 class="text-center">can</h3>
            <h3 class="text-center">contact</h3>
            <h3 class="text-center">me</h3>
            <h3 class="text-center">through</h3>
            <br>
            <a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&to=memahafizh@gmail.com&tf=1"><img src="{% static 'gmail.png' %}"></a>
            <br>
            <a href="https://www.instagram.com/memahafizh/"><img src="{% static 'ig.png' %}"></a>
            <br>
            <a href="https://www.linkedin.com/in/mohammad-hafizh-dwiandra-ramadhan-5251231a3/"><img src="{% static 'linkedin.png' %}"></a>
            <br>
            <a href="https://vsco.co/memahafizh/gallery"><img src="{% static 'vsco.jpeg' %}"></a>
      </div>
{% endblock content %}

home/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

{% endblock meta %}
{% block content %} 
<br>
<br>
<br>
<br>
    <div class="container">
    <table class = "table table-striped" >
        <thead class="thead-dark">
            <th class = "text-light" scope="col">Keterangan</th>
            <th class = "text-light" scope="col">Isi</th>
        </thead>
        <tbody>
            {% for jadwal in schedule %}
        <tr>
            <td class="text-light">Nama Matkul</td>
            <td class = "text-light">{{jadwal.namaMatkul}}</td>
        </tr>
        <tr>
            <td class = "text-light">Nama Dosen</td>
            <td class = "text-light">{{jadwal.dosen}}</td>
        </tr>
        <tr>
            <td class = "text-light">Jumlah SKS</td>
            <td class = "text-light">{{jadwal.sks}}</td>
        </tr>
        <tr>
            <td class = "text-light">deskripsi</td>
            <td class = "text-light">{{jadwal.deskripsi}}</td>
        </tr>
        <tr>
            <td class = "text-light">Semester dan Tahun Ajaran</td>
            <td class = "text-light">{{jadwal.tahun}}</td>
        </tr>
        <tr>
            <td class = "text-light">Ruangan</td>
            <td class = "text-light">{{jadwal.ruang}}</td>    
        </tr>
        {% endfor %}
        </tbody>    
    </table>
</div>
<div class="text-center">
    <a href="{% url 'home:semua' %}"><button type="button" class ="btn btn-light">Kembali</button></a>
</div>
{% endblock content %}

home/templates/exp.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock meta %}
{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-md-4 compfest">
            <img class="cmpfst" src="{% static 'logocompfest-removebg-preview.png' %}" style="width: 270px;height: 270px;background-color: black;margin-top: 1.5vh;margin-left: 1.5vh;max-width: 92%;height: auto;">
            <br>
            <br>
            <h4>Compfest 12</h4>
            <h5>2020</h5>
            <p>Staff of Stage Division</p>
          </div>
          <div class="col-md-2">
          </div>
          <div class="col-md-4 perak">
            <img class="prk" src="{% static 'perak-removebg-preview.png' %}" style="width: 270px;height: 270px;background-color: white;margin-top: 1.5vh;margin-left: 1.5vh;max-width: 92%;height: auto;">
            <br>
            <br>
            <h4>Pesta Rakyat Komputer Fasilkom</h4>
            <h5>2020</h5>
            <p>Staff of Games Division</p>
          </div>
          </div>
        </div>
      </div>
{% endblock content %}

home/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock meta %}
{% block content %}
      <div class="container gal">
        <h2 style="padding: 10px;">Hi!</h2>
        <p style="padding-left: 10px;">Here are some pictures taken and edited by me.</p>
        <p style="padding-left: 10px;">Enjoy!</p>
        <div class="row">
            <div class="col-md-12">
                <div class="thumbnail">
                    <a href="https://vsco.co/memahafizh/media/5b4cb7342c63de1762000001" target="_blank"><img src="{% static 'hihor.jpg' %}" alt="Bundaran HI, Indonesia, 2018" style="width: 100%;"></a>
                        <div class="caption">
                            <p>Bundaran HI, Indonesia, 2018</p>
                        </div>
                </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="thumbnail">
              <a href="https://vsco.co/memahafizh/media/5cbd721b2e637b4d2d000001" target="_blank"><img src="{% static 'hiver.jpg' %}" alt="Bundaran HI, Indonesia, 2019" style="width:100%"></a>
                <div class="caption">
                  <p>Bundaran HI, 2019</p>
                </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="thumbnail">
              <a href="https://vsco.co/memahafizh/media/5f7878792e637b0366000001" target="_blank"><img src="{% static 'senayanver.jpg' %}" alt="Sudirman, Indonesia, 2019" style="width:100%"></a>
                <div class="caption">
                  <p>Sudirman, Indonesia, 2019</p>
                </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="thumbnail">
              <a href="https://vsco.co/memahafizh/media/5a41fe7214aee2081d000001" target="_blank"><img src="{% static 'mbsver.jpg' %}" alt="Marina Bay Sands, Singapore, 2017" style="width:100%"></a>
                <div class="caption">
                  <p>Marina Bay Sands, Singapore, 2017</p>
                </div>
            </div>
          </div>
        </div>
        <div class="row">
            <div class="col-md-12">
              <div class="thumbnail">
                <a href="https://vsco.co/memahafizh/media/5a4289f314aee246cd000009" target="_blank"><img src="{% static 'mbshor.jpg' %}" alt="National Gallery, Singapore, 2017" style="width:100%"></a>
                  <div class="caption">
                    <p>National Gallery, Singapore, 2017</p>
                  </div>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="container more">
                <p>For more, visit <a href="https://vsco.co/memahafizh/gallery" class="here" target="_blank">here</a></p>
            </div>
        </div>
    </div>
{% endblock content %}

home/templates/haltambah.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

{% endblock meta %}
{% block content %} 
<br>
<br>
<br>
<br>
<form action='/haltambah/' method="POST">
    {% csrf_token %}
    <div class="container tambahform">
    <table class = "table" >
        <thead>
            <th scope="col">Keterangan</th>
            <th scope="col">Isi</th>
        </thead>
        <tbody>
            <tr>
                {{form}}
            </tr>
        </tbody>    
    </table>
</div>
<div class="text-center">
    <input type="submit" id ="submit" class="btn btn-success" value="Tambah">
</div>
</form>
{% endblock content %}

home/templates/semua.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

{% endblock meta %}
{% block content %} 
<h1 style="text-align: center; margin-top: 75px;color: white;"> Jadwal Kuliah</h1>
<table class = "table text-light" >
    <thead>
        <th class = "text-light" scope="col">Nama Matkul</th>
        <th class = "text-light" scope="col">Nama Dosen</th>
        <th class = "text-light"  scope="col">Jumlah SKS</th>
        <th class = "text-light" scope="col">Nama Deskripsi</th>
        <th class = "text-light" scope="col">Nama Tahun</th>
        <th class = "text-light" scope="col">Ruangan</th>
        <th class = "text-light" scope="col">Hapus Jadwal</th>
    </thead>
    <tbody>
        {% for jadwal in schedule %}
        <tr>
            <td><a href="{% url 'home:detail' jadwal.id %}" style="color: white;">{{jadwal.namaMatkul}}</a></td>
            <td class = "text-light">{{jadwal.dosen}}</td>
            <td class = "text-light">{{jadwal.sks}}</td>
            <td class = "text-light">{{jadwal.deskripsi}}</td>
            <td class = "text-light">{{jadwal.tahun}}</td>
            <td class = "text-light">{{jadwal.ruang}}</td>
            <td><a href="{% url 'home:hapus' jadwal.id %}"><button type="button" class="btn btn-danger">Hapus</button></a></td>
            
        </tr>
        {% endfor %}
    </tbody>    
</table>
<br>
<div class="text-center">
    <a href="{% url 'home:haltambah' %}"><button type="button" class ="btn btn-light">Tambah Matkul</button></a>
</div>
{% endblock content %}

story6/templates/landing.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

{% endblock meta %}
{% block content %}    
<br>
<br>
<div class="container land" style="text-align: center;margin-top: 30px;background-color: lightgrey;">
    <br>
    <h1>Halo!</h1>
    <br>
    <br>
    <div class="row">
        <div class="col">
            <div class="text-center">
                <a href="{% url 'story6:tambahK' %}"><button type="button" class ="btn btn-light">Tambah Kegiatan</button></a>
            </div>
        </div>
        <div class="col">
            <div class="text-center">
                <a href="{% url 'story6:dataK' %}"><button type="button" class ="btn btn-light">List Kegiatan</button></a>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-default">
    <a class="navbar-brand" href="#">{% if check == 0 %} Profile {% endif %}{% if check == 1 %} Experience {% endif %}{% if check == 2 %} Gallery {% endif %}{% if check == 3 %} Contact {% endif %}{% if check == 4 %} Story 1 {% endif %}{% if check == 5 %} Schedule {% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ">
        <a class="nav-link" href="{% url 'home:index' %}">Profile <span class="sr-only">(current)</span></a>
        <a class="nav-link" href="{% url 'home:exp' %}">Experience</a>
        <a class="nav-link" href="{% url 'home:gallery' %}">Gallery</a>
        <a class="nav-link" href="{% url 'home:contact' %}">Contact</a>
        <a class="nav-link" href="{% url 'story1:story1' %}">Story 1</a>
        <a class="nav-link" href="{% url 'home:semua' %}">Schedule</a>
        <a class="nav-link" href="{% url 'story6:landing' %}">Kegiatan</a>
        <a class="nav-link" href="{% url 'story7:story7' %}">Akordion</a>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
</body>
  
</html>